project:
  type: book
  output-dir: ../docs

book:
  title: "Source separation"
  author:
  - Rohan Gala
  - Smrithi Sunil
  - Kaspar Podgorski
  - Uygar Sümbül
  date: "01/03/2022"
  chapters:
    - index.qmd
    - 00_simulations.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo